"use client";
import NavBar from "./components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./components/Header";
import { useEffect, useState } from "react";
import { SessionProvider } from "next-auth/react";
import { useRouter, usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [page, setPage] = useState(null);
  const path = usePathname();

  useEffect(() => {
    if (path === "/") {
      setPage("popular");
    }
    if (path === "/topRated") {
      setPage("topRated");
    }
    if (path === "/upcoming") {
      setPage("upcoming");
    }
    if (path === "/nowPlaying") {
      setPage("nowPlaying");
    }
    if (path === "/yourList") {
      setPage("yourList");
    }
    if (path === "/login") {
      setPage("login");
    }
  }, [path]);

  return (
    <html lang="en">
      <SessionProvider>
        <body className="mx-10">
          <Header setPage={setPage} />
          <NavBar page={page} />
          <main>{children}</main>
        </body>
      </SessionProvider>
    </html>
  );
}
