"use client";
import NavBar from "./components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./components/Header";
import { useState } from "react";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [page, setPage] = useState("popular");

  return (
    <html lang="en">
      <SessionProvider>
        <body className="mx-10 space-y-4">
          <Header setPage={setPage} />
          <NavBar page={page} setPage={setPage} />
          <main>{children}</main>
        </body>
      </SessionProvider>
    </html>
  );
}
