"use client";
import NavBar from "./components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./components/Header";
import { useEffect, useState } from "react";
import { SessionProvider } from "next-auth/react";
import { useRouter, usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [page, setPage] = useState("popular");
  const router = useRouter();
  const path = usePathname();

  useEffect(() => {
    if (path === "/") {
      setPage("popular");
      router.push("/");
    }
  }, [path]);

  return (
    <html lang="en">
      <SessionProvider>
        <body className="mx-10">
          <Header setPage={setPage} />
          <NavBar page={page} setPage={setPage} />
          <main>{children}</main>
        </body>
      </SessionProvider>
    </html>
  );
}
